name: Maven CD

on: [push]
 
jobs:
 deploy:
  runs-on: windows-latest
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Run build script
      run: |
         chmod +x ./.github/script.sh
         ./.github/script.sh
      shell: bash
         
